SUMMARY = "nInvaders is a Space Invaders clone based on ncurses for ASCII output."
DESCRIPTION = "nInvaders is a space invaders game written for the ncurses terminal control library. It uses ASCII art to draw everything, \
               and it can be played just about anywhere (ex. over dialup)."
HOMEPAGE = "http://ninvaders.sourceforge.net/"
SECTION = "console/games"

DEPENDS = "ncurses (= 5.2)" 
